ranks:
  recruit:
    display: "Recruit"
    cost: 1000
    description: "Your first rank"
    requirements:
      "%statistic_mine_block%": 1000
      "%mcmmo_power_level%": 50
    commands:
      - "lp user %player_name% parent set recruit"

  veteran:
    display: "Veteran"
    cost: 10000
    description: "A seasoned player"
    requirements:
      "%mcmmo_power_level%": 250
      "%playtime_time%": 60000
    commands:
      - "lp user %player_name% parent set veteran"

labels:
  statistic_mine_block: "Blocks Mined"
  mcmmo_power_level: "MCMMO Power Level"
  playtime_time: "Playtime (minutes)"
heads:
  1: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2ZjMGJkZjVhMmVkMjU0MDQ4NGE5YjAxOGQwM2VjNjY3MzE4M2ZmYzJhODFiMDk3YmFjYzJlNGYyZjgzMDEwOCJ9fX0="
  2: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJlYzI3YTRjZjkzNWY2NzFiOTQyZjQ1MmY0OGFhYmY0MmZmZTMzYzBlZDljZGFjNWExOTFkMzY3MThkMjA0MyJ9fX0="

# GUI configuration
# "size" is the number of inventory slots (must be a multiple of 9). If omitted,
# the GUI will default to the smallest multiple of 9 that fits all ranks.
# "layout" maps rank keys to explicit slot indices (0-based). Any ranks not
# listed here will be placed in the next available slot.
gui:
  size: 27
  layout:
    # Example: place the "recruit" rank at slot 10 and "veteran" at slot 12
    # recruit: 10
    # veteran: 12
